#!/usr/bin/env python

import hashlib as hl, pathlib as pl, contextlib as cl, concurrent.futures as cf
import os, sys, enum, struct, stat, tempfile, time

import PIL.Image as pil # https://pillow.readthedocs.io/
try: import numpy as np # https://numpy.org/
except ImportError: np = None # optional for better performance


class adict(dict):
	def __init__(self, *args, **kws):
		super().__init__(*args, **kws)
		self.__dict__ = self

def attrs(o, **attrs):
	for k, v in attrs.items(): setattr(o, k, v)
	return o

@cl.contextmanager
def safe_replacement( path, *open_args,
		mode=None, commit=True, xattrs=None, uidgid=None, **open_kws ):
	'Context to atomically replace file-path if tmp.commit is set w/o exceptions'
	path, exists = str(path), None
	if mode is None:
		try: mode = stat.S_IMODE(os.lstat(path).st_mode)
		except FileNotFoundError: exists = False
	if uidgid is False or exists is False or isinstance(uidgid, tuple): pass
	elif uidgid is True or os.geteuid():
		try: uidgid = (st := os.stat(path)).st_uid, st.st_gid
		except FileNotFoundError: pass
	if xattrs is None and getattr(os, 'getxattr', None): # MacOS
		try: xattrs = dict((k, os.getxattr(path, k)) for k in os.listxattr(path))
		except FileNotFoundError: exists = False
		except OSError as err:
			if err.errno != errno.ENOTSUP: raise
	open_kws.update( delete=False,
		dir=os.path.dirname(path), prefix=os.path.basename(path) + '.' )
	if not open_args: open_kws.setdefault('mode', 'wb')
	if exists is None: exists = os.path.exists(path)
	with tempfile.NamedTemporaryFile(*open_args, **open_kws) as tmp:
		try:
			if mode is not None: os.fchmod(tmp.fileno(), mode)
			if xattrs: list(os.setxattr(tmp.name, k, v) for k, v in xattrs.items())
			if isinstance(uidgid, tuple): os.fchown(tmp.fileno(), *uidgid)
			tmp.file_path, tmp.file_exists, tmp.commit = path, exists, not commit
			yield tmp
			if not tmp.commit: return
			if not tmp.closed:
				tmp.flush()
				try: os.fdatasync(tmp)
				except AttributeError: pass # MacOS
			tmp = os.rename(tmp.name, path)
		finally:
			try: tmp and os.unlink(tmp.name)
			except FileNotFoundError: pass


def img_to_xtg(img, dither=True):
	assert img.size == (480, 800), img.size
	img.convert( '1', dither=pil.Dither.NONE
		if not dither else pil.FLOYDSTEINBERG )
	md5 = hl.md5(data := img.tobytes()).digest()[:8]
	return struct.pack(
		'<4sHHBBI8s', b'XTG\x00', 480, 800,
		0, 0, # color mode, compression
		len(data), md5 ) + data

def img_to_xth(img, grays=(42, 127, 212)):
	assert img.size == (480, 800), img.size
	img.convert('L') # ITU-R 601-2 L = R*.299 + G*.587 + B*.114
	black, dark, light = grays
	if np:
		arr = np.array(img)
		# XTH colors: White=0(00), Light=1(01), Dark=2(10), Black=3(11)
		vals = np.zeros_like(arr, dtype=np.uint8)
		vals[arr < black] = 3
		vals[(arr >= black) & (arr < dark)] = 2
		vals[(arr >= dark) & (arr < light)] = 1
		vals[arr >= light] = 0
		# Vertical scan, columns right-to-left - flip horiz. then transpose (columns -> rows)
		vals = vals[:, ::-1].T
		# Data is two separate bit0 || bit1 planes
		data = ( np.packbits((vals & 1).astype(np.uint8), axis=1).tobytes()
			+ np.packbits(((vals & 2) >> 1).astype(np.uint8), axis=1).tobytes() )
	else:
		pos, bits, img = 0, 8, img.load()
		data = bytearray(480 * 800 // 4); pos_d2 = len(data) // 2
		for x in range(479, -1, -1):
			for y in range(0, 800):
				c = img[x, y]
				c = 3 if c < black else 2 if c < dark else 1 if c < light else 0
				bits -= 1
				data[pos] |= (c & 1) << bits
				data[pos + pos_d2] |= ((c & 2) >> 1) << bits
				if not bits: pos += 1; bits = 8
	return struct.pack(
		'<4sHHBBI8s', b'XTH\x00', 480, 800,
		color_mode := 0, compression := 0,
		len(data), hl.md5(data).digest()[:8] ) + data

def write_xtch(out, imgs, fmt, title=''):
	# Format: hdr 56B || meta 256B || chapters n*96B=0 || index n_pages*16B || pages...
	index = bytearray()
	offset = data_offset = 56 + 256 + len(imgs) * 16
	for img in imgs:
		w, h = struct.unpack_from('<HH', img, 4)
		index += struct.pack('<QIHH', offset, n := len(img), w, h)
		offset += n
	hdr = struct.pack(
		'<4sHHBBBBIQQQQQ',
		b'XTCH' if fmt is fmt.xtch else b'XTC\x00',
		ver := 1, page_count := len(imgs), read_direction := 0,
		has_meta := 1, has_thumbs := 0, has_toc := 0, curr_page := 1,
		meta_offset := 56, index_offset := 56 + 256,
		data_offset, thumb_offset := 0, chapter_offset := 56 + 256 )
	meta = bytearray(256) # title[0:80] author[80:c0] publisher[c0:e0] lang[e0:f0] ...
	title = title.encode()[:0x7f]; meta[:len(title)] = title; struct.pack_into(
		'<IHH', meta, 0xf0, ts := int(time.time()), n_cover := 0, n_chapters := 0 )
	for chunk in [hdr, meta, index, *imgs]: out.write(chunk)


def main(args=None):
	import argparse, textwrap, re
	dd = lambda text: re.sub( r' \t+', ' ',
		textwrap.dedent(text).strip('\n') + '\n' ).replace('\t', '  ')
	parser = argparse.ArgumentParser(
		usage='%(prog)s [options] output.xtc[h] image.png ...',
		formatter_class=argparse.RawTextHelpFormatter, description=dd('''
			Convert image(s) to black-and-white .xtc or 2-bit grayscale .xtch file,
				with images as pages in the same order, intended for Xteink X4 eink reader.
			All images must be 480x800 in size, and won't be rescaled automatically.
			Output file argument can be special "xtc" or "xtch", to convert every image to
				separate files in the current dir, instead of bundling into one multi-page output.'''))
	parser.add_argument('output', help=dd('''
		Name/path to .xtc or .xtch file to produce from all the follow-up image arguments.
		Can be literal "xtc" or "xtch" to convert images to separate files under current dir.
		XTC will produce 1-bit black-or-white output, while XTCH
			format uses 2-bit color (black, white, and 2 shades of gray in-between).'''))
	parser.add_argument('src_images', nargs='+', help=dd('''
		Image file(s) to bundle into xtc/xtch, in the same order,
			in formats supported by python PIL/Pillow module - https://pillow.readthedocs.io/'''))
	parser.add_argument('-t', '--title', metavar='title', default='{p.stem}', help=dd('''
		Title to store in the resulting file metadata, up to 128B. Default: %(default)s
		Additionally formatted using title.format(p=file_path),
			with either output xtc[h] file or input png path (for per-image files).
		Example: --title='image: {p.stem}' (see also python pathlib.Path docs)'''))
	opts = parser.parse_args(sys.argv[1:] if args is None else args)

	out, _, out_ext = opts.output.rpartition('.')
	try: out_fmt = enum.Enum('OutputFormat', 'xtc xtch')[out_ext.lower()]
	except KeyError: parser.error( 'First argument (output) should'
		' be either a filename/path ending in .xtc/.xtch, or literal xtc/xtch' )
	title_fmt = lambda p: (opts.title or '').format(p=pl.Path(p))

	img_bs = {out_fmt.xtc: img_to_xtg, out_fmt.xtch: img_to_xth}[out_fmt]
	with cl.ExitStack() as ctx:
		exe = ctx.enter_context(cf.ThreadPoolExecutor())
		imgs = dict(zip( imgs := list(pl.Path(p) for p in opts.src_images),
			exe.map(lambda p: img_bs(ctx.enter_context(pil.open(p))), imgs) ))
		out_files, out_file = list(), lambda p: \
			out_files.append(tmp := ctx.enter_context(safe_replacement(p))) or tmp
		if out: tasks = [attrs(exe.submit(write_xtch, out_file(
			fn := f'{out}.{out_ext}' ), imgs.values(), out_fmt, title_fmt(fn)), fn=fn)]
		else: tasks = list(
			attrs(exe.submit(write_xtch, out_file(fn), img, out_fmt, title_fmt(p)), fn=fn)
			for fn, p, img in ((f'{p.stem}.{out_ext}', p, img) for p, img in imgs) )
		for task in cf.as_completed(tasks):
			try: task.result()
			except Exception as err: err.add_note(
				f' Failed creating {out_fmt.name} bundle: {task.fn}' ); raise
		for out in out_files: out.commit = True

if __name__ == '__main__': sys.exit(main())
