#!/usr/bin/env python

import pathlib as pl, subprocess as sp, contextlib as cl, hashlib as hl
import datetime as dt, collections as cs, textwrap as tw, zipfile as z
import os, sys, re, io, html, tempfile, uuid, base64, urllib.parse as up

import lxml.html as lxhtml, lxml.etree as lx # https://lxml.de/


dd = lambda text: re.sub( r' \t+', ' ',
	tw.dedent(text).strip('\n') + '\n' ).replace('\t', '  ')
err_fmt = lambda err: f'[{err.__class__.__name__}] {err}'

class adict(dict):
	def __init__(self, *args, **kws):
		super().__init__(*args, **kws)
		self.__dict__ = self
	def __call__(self, **kws): self.update(kws); return self

def str_hash(bs, c=None, key=b'xte-h2e', strip=''):
	if isinstance(bs, (bytes, bytearray)): bs = hl.blake2b(bs, key=key)
	elif hasattr(bs, 'read'): bs = hl.file_digest(bs, lambda: hl.blake2b(key=key))
	else: bs = hl.blake2b(str(bs).encode(), key=key)
	s = base64.urlsafe_b64encode(bs.digest()).decode()
	if not isinstance(strip, dict): strip = dict.fromkeys(map(ord, strip + '-_='))
	s = s.translate(strip)
	if c is None: return s
	for n in range(30): # limit is to avoid unlikely a -> ... -> a loops
		if len(s) < c: s = str_hash(s, c, key, strip)
		if len(s) >= c: break
	else: raise RuntimeError(f'str_hash() failed {[c, key, strip]}')
	return s[:c]

_name_subs = { r'[\\/\?\*;]': '_', r'^\.+': '_', r':': '-_',
	r'<': '(', r'>': ')', r'\*': '+', r'[|!"]': '-', '#': 'N',
	'[\'’,\x00-\x1f]': '', r'\.+\Z': '_', r'\s+\Z': '', r'\s': '_' }
def name_for_fs( name, fallback=...,
		_name_subs=list((re.compile(k), v) for k,v in _name_subs.items()) ):
	if not name and fallback is not ...: return fallback
	for sub_re, sub in _name_subs: name = sub_re.sub(sub, name)
	if len(name) > 80:
		name, _, ext = name.rpartition('.')
		name = '.'.join([name[:70], str_hash(name, 4), ext])
	return name

os.umask(file_repl_umask := os.umask(0))
@cl.contextmanager
def file_replacement(p):
	with tempfile.NamedTemporaryFile( mode='wb', delete=False,
			dir=(p := pl.Path(p)).parent, prefix=f'{p.name}.' ) as tmp:
		tmp.file_path, tmp.commit = p, False
		try:
			os.chmod(tmp.name, 0o666 & ~file_repl_umask)
			yield tmp
			if not tmp.commit: return
			if not tmp.closed: tmp.flush()
			tmp = os.rename(tmp.name, p)
		finally:
			try: tmp and os.unlink(tmp.name)
			except FileNotFoundError: pass


# href_base is for rdrview commands, to match in its output later
# Absolute URLs or base+url in doc won't be replaced by this - only used as fallback
href_base = adict(schema='https://', host='h2e.local', path='h2ex')

class ImgProcErr(Exception): pass

def epub_html_img(ctx, src, srcset, img_proc):
	fmts = ( 'jpg', 'png', 'heif', 'heifs', 'heic', 'heics', 'avci', 'avcs',
		'hif', 'avif', 'jxl', 'jpe', 'jpeg', 'jps', 'jp', 'jif', 'jfif', 'jfi',
		'svg', 'svgz', 'gif', 'webp', 'apng', 'bmp', 'tiff', 'tga' ) # see: magick -list format
	fmt_mime = {'heif-sequence': 'heifs', 'heic-sequence': 'heics', 'svg+xml': 'svg'}
	src_pre, sz_max = f'{href_base.schema}{href_base.host}/', 500 * 2**10 # G400x ~ 35K

	magick_bin = 'magick'
	magick_idfmt = magick_bin, 'identify', '-format', '%m\n'
	magick_conv = lambda p: (magick_bin, f'{p}[0]', *img_proc.opts, 'png:-')

	if not (url := src) and (url := srcset):
		url = list(s.strip().split(None, 1)[0] for s in src.split(',') if s)
		if url: url = url[0]
	if not url: raise ImgProcErr('Missing src URL')

	if m := re.fullmatch(r'(?i)data:image/([-\w+]+);base64,(.*)', url):
		data, fmt = m[2], fmt_mime.get(fmt := m[1].lower()) or fmt
		dec = base64.urlsafe_b64decode if re.search(r'[-+]', data) else base64.standard_b64decode
		tmp = ctx.enter_context( tempfile
			.NamedTemporaryFile(prefix='xteink.html2epub.', suffix=f'.{fmt}') )
		tmp.write(dec(data)); tmp.flush(); del m, data, url, src, srcset # large mem chunks
		p, name = pl.Path(tmp.name), 'img'

	else: # check file and format via imagemagick
		if url.startswith(src_pre):
			url = url[len(src_pre):].removeprefix(f'{href_base.path}/')
			p = img_proc.p / f'./{url}'
		elif re.match(r'[\w/.]', url): p = img_proc.p / f'./{url}'
		else: p = None # absolute URL or something odd
		if not p or not (p := p.resolve()).is_file():
			raise ImgProcErr(f'File missing/inaccessible [ {url} ]')
		fmt = sp.run( [*magick_idfmt, '--', p],
			check=True, stdout=sp.PIPE ).stdout.decode().strip().lower()
		if m := re.match(r'([a-zA-Z]+)', fmt): # strip number-suffix
			fmt, name = m[1], name_for_fs(p.name, 'img')

	if fmt not in fmts: raise ImgProcErr(f'Unrecognized format {fmt!r} [ {p.name} ]')
	with p.open('rb') as src: tag = str_hash(src, 4) # used to dedup images
	proc = sp.Popen(magick_conv(p), stdout=sp.PIPE)
	if len(png := proc.stdout.read(sz_max)) == sz_max:
		proc.kill(); proc.wait(); raise ImgProcErr(f'Size >{sz_max:,d}B [ {p.name} ]')
	if proc.wait(timeout=1): raise ImgProcErr(f'magick-convert falied [ {p.name} ]')
	return adict(name=name, fmt=fmt, tag=tag, png=png)


def epub_html_wrap(title, body, img_proc):
	doc = lxhtml.fragment_fromstring(body, lxhtml.HTMLParser())

	## Fix html elements that don't work in simplistic HtmlSlimParser on eReader
	for pre in doc.xpath('//pre|//code'): # reader app drops these - convert to <p>/<br>
		p = '<br />'.join(html.escape(line) for line in pre.text_content().splitlines())
		p = lxhtml.fragment_fromstring(f'<p>{p}</p>')
		pre.getparent().replace(pre, p)
	for e in doc.xpath('//ul|//ol'): # single-item lists create persistent indent - reader bug
		if len(lis := list(e.xpath('./li'))) != 1: continue
		lis[0].drop_tag(); e.tag = 'div'
	# Non-image media isn't needed, can have massive data-urls from SingleFile
	for e in doc.xpath('//video|//audio|//source'): e.drop_tree()

	## Normalize img tags and images in those
	img_map = dict()
	for e in doc.xpath('//img'): # image srcs get normalized/deduped, added to epub zip
		if not img_proc: e.drop_tree(); continue
		with cl.ExitStack() as ctx:
			try: img = epub_html_img( ctx,
				e.attrib.get('src'), e.attrib.get('srcset'), img_proc )
			except Exception as err:
				if not isinstance(err, ImgProcErr): err = err_fmt(err)
				img = None; img_proc.pr_err(f'WARN: Dropping html-img :: {err}')
		if not img: e.drop_tree(); continue
		if not (img2 := img_map.get(img.tag)):
			img2 = img_map[img.tag] = img
			(fn := img.name).lower().endswith('.png') and (fn := fn[:-4])
			img2.fn = f'{fn}.{img.tag}.png'
		e.attrib.clear(); e.attrib['src'] = img2.fn

	# Despite method=xml here, lxml will easily output broken XML it itself won't validate
	body = lx.tostring(doc, method='xml', encoding='unicode', pretty_print=True)
	doc = dd(f'''
		<?xml version="1.0" encoding="utf-8"?>
		<!DOCTYPE html>
		<html xmlns="http://www.w3.org/1999/xhtml"
			xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="en" lang="en">
		<head><meta charset="utf-8"/><title>{html.escape(title)}</title></head>
		<body>''') + f'\n{body}\n</body>\n</html>'
	# lx.fromstring(doc, lxhtml.HTMLParser(recover=False))
	return doc, list(img_map.values())


def html_to_epub(title, doc, img_list, pp=None):
	'Creates epub container with xml boilerplate around html in there'
	# See https://en.wikipedia.org/wiki/EPUB for details
	# Spec - https://www.w3.org/TR/epub-33/
	# https://github.com/IDPF/epub3-samples/ for more useful examples
	with z.ZipFile(epub := io.BytesIO(), 'w') as meta: meta.writestr(
		'mimetype', 'application/epub+zip', compress_type=z.ZIP_STORED )
	with z.ZipFile(epub, 'a', z.ZIP_DEFLATED) as body:
		html_bid = html.escape(f'urn:uuid:{uuid.uuid4()}')
		html_ts = html.escape( dt.datetime
			.now(dt.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ') )
		html_title = html.escape(title)
		body.writestr('META-INF/container.xml', s := dd('''
			<?xml version="1.0" encoding="utf-8"?>
			<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
			<rootfiles>
				<rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
			</rootfiles>
			</container>'''))
		pp.xml(s)
		body.writestr('OEBPS/content.opf', opf := dd(f'''
			<?xml version="1.0" encoding="utf-8"?>
			<package xmlns="http://www.idpf.org/2007/opf" version="3.0"
				unique-identifier="BookId" prefix="rendition: http://www.idpf.org/vocab/rendition/#">
			<metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
				<dc:identifier id="BookId">{html_bid}</dc:identifier>
				<dc:title>{html_title}</dc:title>
				<dc:language>en</dc:language>
				<meta property="dcterms:modified">{html_ts}</meta>
				<meta property="rendition:layout">reflowable</meta>
				<meta property="rendition:orientation">auto</meta>
				<meta property="rendition:spread">auto</meta>
			</metadata>
			<manifest>
				<item id="text" href="text.xhtml" media-type="application/xhtml+xml"/>
				<item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
				<item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>{{img_items}}
			</manifest>
			<spine toc="ncx"><itemref idref="text"/></spine>
			</package>''').format(img_items=''.join(
				f'\n  <item id="img.{img.tag}" href="{img.fn}" media-type="image/png"/>'
				for img in img_list )))
		pp.opf(opf)
		body.writestr('OEBPS/text.xhtml', doc)
		pp.xhtml(doc)
		body.writestr('OEBPS/toc.ncx', s := dd(f'''
			<?xml version="1.0" encoding="utf-8"?>
			<!DOCTYPE ncx PUBLIC "-//NISO//DTD ncx 2005-1//EN"
				"http://www.daisy.org/z3986/2005/ncx-2005-1.dtd">
			<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1" xml:lang="en">
			<head>
				<meta name="dtb:uid" content="{html_bid}"/>
				<meta name="dtb:depth" content="1"/>
				<meta name="dtb:totalPageCount" content="0"/>
				<meta name="dtb:maxPageNumber" content="0"/>
			</head>
			<docTitle>
				<text>{html_title}</text>
			</docTitle>
			<navMap>
				<navPoint id="navPoint-1" playOrder="1">
					<navLabel><text>{html_title}</text></navLabel>
					<content src="text.xhtml"/>
				</navPoint>
			</navMap>
			</ncx>'''))
		pp.ncx(s)
		body.writestr('OEBPS/nav.xhtml', s := dd('''
			<?xml version="1.0" encoding="utf-8"?>
			<!DOCTYPE html>
			<html xmlns="http://www.w3.org/1999/xhtml"
				xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="en" lang="en">
			<head><meta charset="utf-8"/><title>Table of Contents</title></head>
			<body>
				<nav epub:type="toc" id="toc">
					<h1>{html_title}</h1>
					<ol><li><a href="text.xhtml">{html_title}</a></li></ol>
				</nav>
				<nav epub:type="landmarks" hidden="hidden">
					<h2>Guide</h2>
					<ol><li><a epub:type="bodymatter" href="text.xhtml">{html_title}</a></li></ol>
				</nav>
			</body>
			</html>'''))
		pp.nav(s)
		for img in img_list: body.writestr(f'OEBPS/{img.fn}', img.png)
	return epub.getvalue()


def main(args=None):
	print_types = 'input body xhtml xml opf ncx nav'.split()

	import argparse
	parser = argparse.ArgumentParser(
		usage='%(prog)s [options] file.html ...',
		formatter_class=argparse.RawTextHelpFormatter, description=dd('''
			Converts HTML files to simple epub files, without chapters,
				styling, complicated tags and similar crap, optimized for simple eink devices,
				where all that crap makes these files unreadable or crashes their reader apps,
				targeting Xteink X4 eReader firmwares in particular.
			Uses https://github.com/eafer/rdrview tool to strip-down/simplify html first,
				then fixes couple html quirks that tend not to work/render in reader apps,
				and then puts epub wrapper around the file (zip container + META-INF + oebps).
			Requires imagemagick command-line tools ("magick" command)
				to check and convert any known image formats to downscaled grayscale PNGs.
			Works offline, does not fetch anything (rdrview shouldn't either),
				but can load/pack images from local files relative to html file.'''),
		epilog=dd('''
			Resulting EPUB structure should be:
			 - Title from either page title or excerpt, as extracted by rdrview --meta.
			 - No cover image, random urn:uuid:... for book ID, current date/time, no other metadata.
			 - EPUB 2 toc.ncx and EPUB 3 nav.xhtml, both with single chapter, using same doc title.
			 - Full rdrview HTML-text extract for single-chapter body, with xml/html/xhtml headers.
			 - Images for <img ...> tags are extracted from data-URLs or loaded via relative urls,
					then imagemagick-downscaled/converted for resulting epub, if found/recognized.
					Non-src attributes on <img ...> tags get stripped to disable
						any on-device scaling via width=/height= or other image tweaks.
			 - Other media tags like <audio>/<video>/<source ...> are removed.
			 - Reader-problematic <pre>/<code> tags replaced by <p> with <br/>-separated lines.
			 - Single-item <ol>/<ul> lists are converted to <div> - reader-bug with stuck indents.

			libxml2 tools and -p/--print option can be used to inspect resulting xhtml:
				./xteink-html2epub bad.html -qp xhtml | xmllint --pretty 2 - | less''') + ' ')

	group = parser.add_argument_group('Inputs/outputs')
	group.add_argument('html_files', nargs='+', help=dd('''
		HTML file(s) to convert. Always processed by rdrview tool first to normalize contents.
		Output epub files are generated next to those, replacing filename extension with .epub'''))
	group.add_argument('-o', '--out-file', metavar='file', help=dd('''
		Output filename to use instead of putting .epub files next to source HTML ones.
		Only allowed with a single input file.'''))
	group.add_argument('-O', '--out-dir', metavar='dir', help=dd('''
		Directory to put output file(s) to, under same filename(s) derived from source files.
		Must be an existing dir, will NOT be created automatically. Filenames must not conflict.'''))

	group = parser.add_argument_group('Text processing options')
	group.add_argument('-r', '--relaxed', action='store_true', help=dd('''
		Disable some rdrview tool content-processing heuristics, leaving more elements
			in resulting main HTML document body, which can be useful if it removes too much.
		Requires rdrview supporting --disable-heuristic option,
			see https://github.com/eafer/rdrview/pull/49 for status on that.
		It's same diff as sanity-checks default-detect when pandoc is available.'''))
	group.add_argument('-C', '--no-checks', action='store_true', help=dd('''
		Disable optional/opportunistic sanity-checks on resulting HTML.
		These are currently only performed if rdrview supports --disable-heuristic
			option and "pandoc" tool/binary available via PATH, auto-disabled otherwise.'''))

	group = parser.add_argument_group('Image processing')
	group.add_argument('--img-strip', action='store_true',
		help='Remove all images instead of any kind of processing.')
	group.add_argument('--img-proc', metavar='opts', help=dd('''
			ImageMagick image-processing options for all images that are packed in epub file.
			Options are space-separated, don't need shell-quoting,
				but can include URL-escapes for spaces (%%20) or other characters,
				with extra %%%%-escapes supported in %%<2hexdigits> places (e.g. %%%%12 -> %%12).
			See https://imagemagick.org/command-line-options/ on each one for more details.
			Default: %(default)s'''),
		default='-scale 400x700> -grayscale rec601luma -brightness-contrast -20x50 -sharpen 1')

	group = parser.add_argument_group('Console outputs')
	group.add_argument('-q', '--quiet', action='store_true', help='Suppress normal output.')
	group.add_argument('-p', '--print', metavar='type[:n]', help=dd(f'''
		Print specific HTML processing stage to stdout for Nth file (default is 1 - first one).
		Should be in "type[:n]" format, with "type" being one of: {' '.join(print_types)}
		Intended to check what went wrong during processing.'''))

	opts = parser.parse_args(sys.argv[1:] if args is None else args)

	class pr_null_cls: __bool__ = lambda s: False; __call__ = lambda s,*a,**kw: None
	pr_null = pr_null_cls()
	pr_out = pr_out_nq = lambda *a,**kw: print(*a, **kw, flush=True)
	pr_err = lambda *a,**kw: print(*a, **kw, file=sys.stderr, flush=True)
	if opts.quiet: pr_out = pr_null
	if not opts.print: pt = pn = None
	pp = adict((pt.replace(*'-_'), dict.fromkeys(range(1, 999), pr_null)) for pt in print_types)
	if opts.print:
		pt, pn = (opts.print.split(':', 1) + [1])[:2]
		if pt not in print_types: parser.error(f'Unrecognized -p/--print value: {opts.print}')
		pp[pt.lower().replace(*'-_')][int(pn)] = pr_out_nq
	if (p_dst := opts.out_file) and len(opts.html_files) > 1:
		parser.error('-o/--out-file option is only allowed with single input file')
	if p_dst_dir := opts.out_dir:
		if p_dst: parser.error('-o/--out-file and -O/--out-dir options are mutually exclusive')
		if not (p_dst_dir := pl.Path(p_dst_dir)).is_dir():
			parser.error('-O/--out-dir is missing/bogus/inaccessible')
	img_proc = tuple(up.unquote(re.sub(
		r'%%([0-9A-Fa-f]{2})', r'%25\1', opt )) for opt in opts.img_proc.split())

	rdrview_bin = 'rdrview'
	rdrview_meta = rdrview_bin, '--meta',
	rdrview_conv = ( rdrview_bin, '--html', '--base',
		f'{href_base.schema}{href_base.host}/{href_base.path}/' )
	rdrview_opts_relaxed = '--disable-heuristic', 'unlikely'
	if opts.relaxed: rdrview_conv += rdrview_opts_relaxed

	if ( rdrview_check := not (opts.relaxed or opts.no_checks) and
			'[proc-flags]' in sp.run([rdrview_bin, '-h'], stderr=sp.PIPE).stderr.decode() ):
		try: sp.run(['pandoc', '--version'], stdout=sp.DEVNULL)
		except FileNotFoundError: rdrview_check = pr_out(
			'WARN: Disabling rdrview-html sanity-checks due to missing pandoc tool' )
		else: rdrview_check, pandoc_conv = ( rdrview_conv +
			rdrview_opts_relaxed, ('pandoc', '--quiet', '--from=html', '--to=plain') )

	files, p_epub_conflicts = list(), cs.defaultdict(list)
	for n, p in enumerate(map(pl.Path, opts.html_files), 1):
		if not p.is_file(): parser.error(f'Input file is missing/bogus/inaccessible: {p}')
		if pr := pp.input[n]: pr(p.read_text().strip())

		proc = sp.run([*rdrview_meta, '--', p], stdout=sp.PIPE, check=True)
		meta, key = adict(), None
		for line in proc.stdout.decode().splitlines():
			if not line.strip(): continue
			elif m := re.fullmatch(r'(\w+):\s+(.*)', line):
				meta[key := m[1].lower()] = m[2].strip()
			elif key and (m := re.fullmatch(r'\s+(.*)', line)): meta[key] += f' {m[1]}'
		if meta.get('readerable', '').lower() != 'yes':
			parser.error(f'ERROR: rdrview failed to process file: {p}')

		proc = sp.run([*rdrview_conv, '--', p], stdout=sp.PIPE, check=True)
		body = proc.stdout.decode()
		if pr := pp.body[n]: pr(body.strip())

		if rdrview_check:
			proc = sp.run([*rdrview_check, '--', p], stdout=sp.PIPE, check=True)
			if (body_chk := proc.stdout.decode()) != body:
				import difflib; txt_base, txt_relax = (
					sp.run(pandoc_conv, input=html.encode(), stdout=sp.PIPE, check=True)
					.stdout.decode().strip().split('\n') for html in (body, body_chk) )
				if diff := list(difflib.unified_diff(txt_relax, txt_base, n=2)):
					pr_out(f'SANITY-CHECK: rdrview diffs for base/relaxed run-modes in [ {p} ]')
					for line in diff[3:]: pr_out(f'  {line.rstrip()}')

		if p_dst: p_epub = p_dst
		else:
			p_epub = p.parent / ((p.stem if len(p.suffix) <= 7 else p.name) + '.epub')
			if str(p).lower() == str(p_epub).lower(): p_epub = p_epub.with_suffix('.proc.epub')
			if p_dst_dir: p_epub = p_dst_dir / p_epub.name
		files.append(adict(p=p, n=n, p_epub=p_epub, meta=meta, body=body))
		p_epub_conflicts[p_epub].append(p)

	for p_epub, ps in p_epub_conflicts.items():
		if len(ps) == 1: continue
		pr_err(f'ERROR: Output filename conflict [ {p_epub} ] for source files:')
		for p in ps: pr_err(f'  {p}')
		p_epub_conflicts = None
	if not p_epub_conflicts: return 1

	for fx in files:
		fx.title = fx.meta.get('title') or fx.meta.get('excerpt') or fx.p.stem
		html, img_list = epub_html_wrap( fx.title, fx.body,
			img_proc=not opts.img_strip and adict(
				pr_err=pr_err, p=fx.p.resolve().parent, opts=img_proc ) )
		fx.epub = html_to_epub( fx.title, html,
			img_list, pp=adict((k, pp[k][fx.n]) for k in pp) )

	with cl.ExitStack() as ctx:
		for fx in files:
			out = fx.out = ctx.enter_context(file_replacement(fx.p_epub))
			out.write(fx.epub)
		for fx in files:
			pr_out(f'Created epub file: {fx.p_epub}')
			fx.out.commit = True

if __name__ == '__main__': sys.exit(main())
