#!/usr/bin/env python

import pathlib as pl, subprocess as sp, contextlib as cl
import datetime as dt, collections as cs, textwrap as tw, zipfile as z
import os, sys, re, io, html, tempfile, uuid

import lxml.html as lxhtml, lxml.etree as lx # https://lxml.de/


dd = lambda text: re.sub( r' \t+', ' ',
	tw.dedent(text).strip('\n') + '\n' ).replace('\t', '  ')

class adict(dict):
	def __init__(self, *args, **kws):
		super().__init__(*args, **kws)
		self.__dict__ = self
	def __call__(self, **kws): self.update(kws); return self

@cl.contextmanager
def file_replacement(p):
	with tempfile.NamedTemporaryFile( mode='wb', delete=False,
			dir=(p := pl.Path(p)).parent, prefix=f'{p.name}.' ) as tmp:
		tmp.file_path, tmp.commit = p, False
		try:
			yield tmp
			if not tmp.commit: return
			if not tmp.closed: tmp.flush()
			tmp = os.rename(tmp.name, p)
		finally:
			try: tmp and os.unlink(tmp.name)
			except FileNotFoundError: pass


def epub_html_wrap(title, body):
	doc = lxhtml.fragment_fromstring(body, lxhtml.HTMLParser())
	for tag in 'pre', 'code':
		for pre in doc.xpath(f'//{tag}'):
			p = '<br />'.join(html.escape(line) for line in pre.text_content().splitlines())
			p = lxhtml.fragment_fromstring(f'<p>{p}</p>')
			pre.getparent().replace(pre, p)
	# lxml will output broken XML that it itself won't validate anyway
	body = lx.tostring(doc, method='xml', encoding='unicode', pretty_print=True)
	doc = dd(f'''
		<?xml version="1.0" encoding="utf-8"?>
		<!DOCTYPE html>
		<html xmlns="http://www.w3.org/1999/xhtml"
			xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="en" lang="en">
		<head><meta charset="utf-8"/><title>{html.escape(title)}</title></head>
		<body>''') + f'\n{body}\n</body>\n</html>'
	# lx.fromstring(doc, lxhtml.HTMLParser(recover=False))
	return doc

def html_to_epub(title, doc):
	'Creates epub container with xml boilerplate around html in there'
	# See https://en.wikipedia.org/wiki/EPUB for details
	# Spec - https://www.w3.org/TR/epub-33/
	# https://github.com/IDPF/epub3-samples/ for more useful examples
	with z.ZipFile(epub := io.BytesIO(), 'w') as meta: meta.writestr(
		'mimetype', 'application/epub+zip', compress_type=z.ZIP_STORED )
	with z.ZipFile(epub, 'a', z.ZIP_DEFLATED) as body:
		html_bid = html.escape(f'urn:uuid:{uuid.uuid4()}')
		html_ts = html.escape( dt.datetime
			.now(dt.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ') )
		html_title = html.escape(title)
		body.writestr('META-INF/container.xml', dd('''
			<?xml version="1.0" encoding="utf-8"?>
			<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
			<rootfiles>
				<rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
			</rootfiles>
			</container>'''))
		body.writestr('OEBPS/content.opf', dd(f'''
			<?xml version="1.0" encoding="utf-8"?>
			<package xmlns="http://www.idpf.org/2007/opf" version="3.0"
				unique-identifier="BookId" prefix="rendition: http://www.idpf.org/vocab/rendition/#">
			<metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
				<dc:identifier id="BookId">{html_bid}</dc:identifier>
				<dc:title>{html_title}</dc:title>
				<dc:language>en</dc:language>
				<meta property="dcterms:modified">{html_ts}</meta>
				<meta property="rendition:layout">reflowable</meta>
				<meta property="rendition:orientation">auto</meta>
				<meta property="rendition:spread">auto</meta>
			</metadata>
			<manifest>
				<item id="text" href="text.xhtml" media-type="application/xhtml+xml"/>
				<item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
				<item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
			</manifest>
			<spine toc="ncx"><itemref idref="text"/></spine>
			</package>'''))
		body.writestr('OEBPS/text.xhtml', doc)
		body.writestr('OEBPS/toc.ncx', dd(f'''
			<?xml version="1.0" encoding="utf-8"?>
			<!DOCTYPE ncx PUBLIC "-//NISO//DTD ncx 2005-1//EN"
				"http://www.daisy.org/z3986/2005/ncx-2005-1.dtd">
			<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1" xml:lang="en">
			<head>
				<meta name="dtb:uid" content="{html_bid}"/>
				<meta name="dtb:depth" content="1"/>
				<meta name="dtb:totalPageCount" content="0"/>
				<meta name="dtb:maxPageNumber" content="0"/>
			</head>
			<docTitle>
				<text>{html_title}</text>
			</docTitle>
			<navMap>
				<navPoint id="navPoint-1" playOrder="1">
					<navLabel><text>{html_title}</text></navLabel>
					<content src="text.xhtml"/>
				</navPoint>
			</navMap>
			</ncx>'''))
		body.writestr('OEBPS/nav.xhtml', dd('''
			<?xml version="1.0" encoding="utf-8"?>
			<!DOCTYPE html>
			<html xmlns="http://www.w3.org/1999/xhtml"
				xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="en" lang="en">
			<head><meta charset="utf-8"/><title>Table of Contents</title></head>
			<body>
				<nav epub:type="toc" id="toc">
					<h1>{html_title}</h1>
					<ol><li><a href="text.xhtml">{html_title}</a></li></ol>
				</nav>
				<nav epub:type="landmarks" hidden="hidden">
					<h2>Guide</h2>
					<ol><li><a epub:type="bodymatter" href="text.xhtml">{html_title}</a></li></ol>
				</nav>
			</body>
			</html>'''))
	return epub.getvalue()


def main(args=None):
	print_types = 'input body xhtml'.split()

	import argparse
	parser = argparse.ArgumentParser(
		usage='%(prog)s [options] file.html ...',
		formatter_class=argparse.RawTextHelpFormatter, description=dd('''
			Converts HTML files to simple epub files, without chapters,
				styling, complicated tags and similar crap, optimized for simple eink devices,
				where all that crap makes these files unreadable or crashes their reader apps,
				targeting Xteink X4 eReader firmwares in particular.
			Uses https://github.com/eafer/rdrview tool to strip-down/simplify html first,
				then fixes couple html quirks that tend not to work/render in reader apps,
				and then puts epub wrapper around the file (zip container + META-INF + oebps).'''),
		epilog=dd('''
			Resulting EPUB structure should be:
			 - Title from either page title or excerpt, as extracted by rdrview --meta.
			 - No cover image, random urn:uuid:... for book ID, current date/time, no other metadata.
			 - EPUB 2 toc ncx and EPUB 3 nav xhtml, both with single chapter, using same doc title.
			 - Full rdrview HTML-text extract for single-chapter body, with xml/html/xhtml headers.
			 - Reader-problematic <pre>/<code> tags replaced by <p> with <br/>-separated lines.''')+' ')
		# XXX: images - check how rdrview handles those, maybe extract/convert/insert
	parser.add_argument('html_files', nargs='+', help=dd('''
		HTML file(s) to convert. Always processed by rdrview tool first to normalize contents.
		Output epub files are generated next to those, replacing filename extension with .epub'''))
	parser.add_argument('-o', '--out-file', metavar='file', help=dd(f'''
		Output filename to use instead of putting .epub files next to source HTML ones.
		Only allowed with a single input file.'''))
	parser.add_argument('-O', '--out-dir', metavar='dir', help=dd(f'''
		Directory to put output file(s) to, under same filename(s) derived from source files.
		Must be an existing dir, will NOT be created automatically. Filenames must not conflict.'''))
	parser.add_argument('-p', '--print', metavar='type[:n]', help=dd(f'''
		Print specific HTML processing stage to stdout for Nth file (default is 1 - first one).
		Should be in "type[:n]" format, with "type" being one of: {', '.join(print_types)}.
		Intended to check what went wrong during processing.'''))
	parser.add_argument('-q', '--quiet', action='store_true', help='Suppress normal output.')
	opts = parser.parse_args(sys.argv[1:] if args is None else args)

	p_out = lambda *a,**kw: print(*a, **kw, flush=True)
	p_err = lambda *a,**kw: print(*a, **kw, file=sys.stderr, flush=True)
	if opts.quiet: p_out = lambda *a,**kw: None
	if not opts.print: pt = pn = None
	pp = adict((pt.replace(*'-_'), dict.fromkeys(range(1, 999))) for pt in print_types)
	if opts.print:
		pt, pn = (opts.print.split(':', 1) + [1])[:2]
		if pt not in print_types: parser.error(f'Unrecognized -p/--print value: {opts.print}')
		pp[pt.lower().replace(*'-_')][int(pn)] = True
	if (p_dst := opts.out_file) and len(opts.html_files) > 1:
		parser.error('-o/--out-file option is only allowed with single input file')
	if p_dst_dir := opts.out_dir:
		if p_dst: parser.error('-o/--out-file and -O/--out-dir options are mutually exclusive')
		if not (p_dst_dir := pl.Path(p_dst_dir)).is_dir():
			parser.error('-O/--out-dir is missing/bogus/inaccessible')

	files, p_epub_conflicts = list(), cs.defaultdict(list)
	for n, p in enumerate(map(pl.Path, opts.html_files), 1):
		if not p.is_file(): parser.error(f'Input file is missing/bogus/inaccessible: {p}')
		if pp.input[n]: p_out(p.read_text().strip())
		proc = sp.run(['rdrview', '--meta', '--', p], stdout=sp.PIPE, check=True)
		meta, key = adict(), None
		for line in proc.stdout.decode().splitlines():
			if not line.strip(): continue
			elif m := re.fullmatch(r'(\w+):\s+(.*)', line):
				meta[key := m[1].lower()] = m[2].strip()
			elif key and (m := re.fullmatch(r'\s+(.*)', line)): meta[key] += f' {m[1]}'
		if meta.get('readerable', '').lower() != 'yes':
			parser.error(f'ERROR: rdrview failed to process file: {p}')
		proc = sp.run(['rdrview', '--html', '--', p], stdout=sp.PIPE, check=True)
		body = proc.stdout.decode()
		if pp.body[n]: p_out(body.strip())
		if p_dst: p_epub = p_dst
		else:
			p_epub = p.parent / ((p.stem if len(p.suffix) <= 7 else p.name) + '.epub')
			if str(p).lower() == str(p_epub).lower(): p_epub = p_epub.with_suffix('.proc.epub')
			if p_dst_dir: p_epub = p_dst_dir / p_epub.name
		files.append(adict(p=p, n=n, p_epub=p_epub, meta=meta, body=body))
		p_epub_conflicts[p_epub].append(p)

	for p_epub, ps in p_epub_conflicts.items():
		if len(ps) == 1: continue
		p_err(f'ERROR: Output filename conflict [ {p_epub} ] for source files:')
		for p in ps: p_err(f'  {p}')
		p_epub_conflicts = None
	if not p_epub_conflicts: return 1

	for fx in files:
		fx.title = fx.meta.get('title') or fx.meta.get('excerpt') or fx.p.stem
		fx.html = epub_html_wrap(fx.title, fx.body)
		if pp.xhtml[fx.n]: p_out(fx.html)
		fx.epub = html_to_epub(fx.title, fx.html)

	with cl.ExitStack() as ctx:
		for fx in files:
			out = fx.out = ctx.enter_context(file_replacement(fx.p_epub))
			out.write(fx.epub)
		for fx in files:
			p_out(f'Created epub file: {fx.p_epub}')
			fx.out.commit = True

if __name__ == '__main__': sys.exit(main())
